### ISSUE TITLE
StreamRadio crashing when toggling between stations

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Haiku-Radio#12]
- hrev53242 x86_64
- StreamRadio build from HaikuArchives source using gcc8.3
- Launched from terminal: LD_PRELOAD=libroot_debug.so MALLOC_DEBUG=g StreamRadio
- Toggling between stations will eventually trigger debugger. Previous staion was 'stopped" before toggling to next station.
- Debug output below:

Debug information for team /boot/home/HaikuArchives/Haiku-Radio/dist/StreamRadio (3025):
CPU(s): 8x Intel Core™ i7-3770
Memory: 15.88 GiB total, 869.98 MiB used
Haiku revision: hrev53242 Jul 11 2019 19:13:24 (x86_64)

Active Threads:
	thread 3025: StreamRadio (main)
	thread 3032: MouseTrackingThread 
	thread 3033: team 3025 debug task 
	thread 3030: w>StreamRadio 
		state: Call (generic segfault)

		Frame		IP			Function Name
		-----------------------------------------------
		00000000	0x1fffd774e7f	_kern_debugger + 0x7 
			Disassembly:
				_kern_debugger:
				0x000001fffd774e78:   48c7c0e1000000  mov $0xe1, %rax
				0x000001fffd774e7f:             0f05  syscall  <--

		0x7fc9b4756b80	0x1fffd81e25d	panic(char const*, ...) + 0xad 
		0x7fc9b4756b80	0x7ffff605223b	commpage_signal_handler + 0x2b 
		0x7fc9b4756f70	0x48cffeca9c	StreamIO::Open() + 0xc 
		0x7fc9b4757030	0x48cffed6d1	StreamPlayer::StreamPlayer(Station*, BLooper*) + 0xb1 
		0x7fc9b4757070	0x48cffe2d0a	MainWindow::TogglePlay(StationListViewItem*) + 0x7a 
		0x7fc9b4757100	0x48cffe3451	MainWindow::MessageReceived(BMessage*) + 0x5d1 
		0x7fc9b4757330	0x197e609c8d9	BWindow::DispatchMessage(BMessage*, BHandler*) + 0x89 
		0x7fc9b47573c0	0x197e60989eb	BWindow::task_looper() + 0x1bb 
		0x7fc9b47573e0	0x197e5fdfa6b	BLooper::_task0_(void*) + 0x1b 
		0x7fc9b4757400	0x1fffd773c27	thread_entry + 0x17 
		00000000	0x7ffff6052260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x000001fffd774e81
			  rsp:	0x00007fc9b4756688
			  rbp:	0x00007fc9b4756b70
			  rax:	0x00000000000000e1
			  rbx:	0x00007fc9b47566b0
			  rcx:	0x000001fffd774e81
			  rdx:	0x00007fc9b4756191
			  rsi:	0x0000000000000001
			  rdi:	0x00007fc9b47566b0
			   r8:	0x00007fc9b4753b54
			   r9:	0x00000000fffffff0
			  r10:	0x00007fc9b47566b0
			  r11:	0x0000000000003206
			  r12:	0x00007fc9b4756b90
			  r13:	0x0000000000dcfdf0
			  r14:	0x0000000001a80dd0
			  r15:	0x00000000030defc8
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	29386	0x1c6d64c000	0x1c6d7ae000	0x1c6d9ae000	0x1c6d9c2000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	29405	0x26dc362000	0x26dc3cc000	0x26dc5cb000	0x26dc5d6000	lib    	/boot/system/lib/libssl.so.1.0.0
	29396	0x46ebcd7000	0x46ebd2c000	0x46ebf2c000	0x46ebf2f000	lib    	/boot/system/lib/libicule.so.57.1
	29384	0x48cffc6000	0x48cfff3000	0x48d01f3000	0x48d01f6000	app    	/boot/home/HaikuArchives/Haiku-Radio/dist/StreamRadio
	29389	0x4e1c9c6000	0x4e1ca2c000	0x4e1cc2c000	0x4e1cc31000	lib    	/boot/system/lib/libbnetapi.so
	29392	0x544d104000	0x544d11a000	0x544d319000	0x544d31a000	lib    	/boot/system/lib/libgcc_s.so.1
	29403	0xc5e982f000	0xc5e9870000	0xc5e9a6f000	0xc5e9a78000	lib    	/boot/system/lib/libnetwork.so
	29395	0xc61c9e1000	0xc61c9ed000	0xc61cbec000	0xc61cbee000	lib    	/boot/system/lib/libicuio.so.57.1
	29394	0xd2daf1f000	0xd2db19c000	0xd2db39b000	0xd2db3b0000	lib    	/boot/system/lib/libicui18n.so.57.1
	29402	0x1050cd02000	0x1050cdfd000	0x1050cffd000	0x1050d000000	lib    	/boot/system/lib/libtextencoding.so
	29401	0x1134f0ce000	0x1134f1a1000	0x1134f3a1000	0x1134f3a2000	lib    	/boot/system/lib/libzstd.so.1.3.8
	29398	0x1207cf33000	0x1207cf62000	0x1207d162000	0x1207d196000	lib    	/boot/system/lib/libicutu.so.57.1
	29397	0x1343b45b000	0x1343b466000	0x1343b666000	0x1343b667000	lib    	/boot/system/lib/libiculx.so.57.1
	29390	0x14d70f78000	0x14d7102c000	0x14d7122c000	0x14d71238000	lib    	/boot/system/lib/libmedia.so
	29391	0x159f6f15000	0x159f706b000	0x159f726b000	0x159f7278000	lib    	/boot/system/lib/libxml2.so.2.9.9
	29383	0x168cb9ff000	0x168cba20000	0x168cbc1f000	0x168cbc22000	lib    	/boot/system/runtime_loader
	29388	0x189e00f9000	0x189e010e000	0x189e030d000	0x189e030f000	lib    	/boot/system/lib/libtranslation.so
	29387	0x197e5e88000	0x197e61a0000	0x197e63a0000	0x197e63ce000	lib    	/boot/system/lib/libbe.so
	29399	0x1af075c5000	0x1af0775d000	0x1af0795c000	0x1af07971000	lib    	/boot/system/lib/libicuuc.so.57.1
	29400	0x1bb699f8000	0x1bb69a14000	0x1bb69c13000	0x1bb69c14000	lib    	/boot/system/lib/libz.so.1.2.11
	29404	0x1c942fc2000	0x1c9431c4000	0x1c9433c3000	0x1c9433ec000	lib    	/boot/system/lib/libcrypto.so.1.0.0
	29393	0x1ca93320000	0x1ca94b9e000	0x1ca94d9d000	0x1ca94d9e000	lib    	/boot/system/lib/libicudata.so.57.1
	29406	0x1da422fa000	0x1da42301000	0x1da42500000	0x1da42501000	lib    	/boot/system/lib/libbsd.so
	29385	0x1fffd733000	0x1fffd894000	0x1fffda94000	0x1fffdae6000	lib    	/boot/system/lib/libroot_debug.so
	29382	0x7ffff6052000	0x7ffff605a000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	106281	0x002e6000	0x004e6000	      2048	rw-        	full          	guarded_heap_area
	106283	0x00633000	0x00833000	      2048	rw-        	full          	guarded_heap_area
	106282	0x00866000	0x00a66000	      2048	rw-        	full          	guarded_heap_area
	106272	0x00b11000	0x00d11000	      2048	rw-        	full          	guarded_heap_area
	106267	0x00d2a000	0x00f2a000	      2048	rw-        	full          	guarded_heap_area
	106292	0x00fcb000	0x011cb000	      2048	rw-        	full          	guarded_heap_area
	106295	0x0120e000	0x0140e000	      2048	rw-        	full          	guarded_heap_area
	106291	0x0141a000	0x0161a000	      2048	rw-        	full          	guarded_heap_area
	106288	0x01676000	0x01876000	      2048	rw-        	full          	guarded_heap_area
	106317	0x01885000	0x01a85000	      2048	rw-        	full          	guarded_heap_area
	106310	0x01b82000	0x01d82000	      2048	rw-        	full          	guarded_heap_area
	106326	0x01e20000	0x02020000	      2048	rw-        	full          	guarded_heap_area
	106309	0x02152000	0x02352000	      2048	rw-        	full          	guarded_heap_area
	106304	0x0254d000	0x0274d000	      2048	rw-        	full          	guarded_heap_area
	106330	0x02ee0000	0x030e0000	      2048	rw-        	full          	guarded_heap_area
	106329	0x03475000	0x03675000	      2048	rw-        	full          	guarded_heap_area
	106301	0x03a74000	0x03c74000	      2048	rw-        	full          	guarded_heap_area
	106298	0x054ef000	0x056ef000	      2048	rw-        	full          	guarded_heap_area
	106287	0x0570b000	0x0590b000	      2048	rw-        	full          	guarded_heap_area
	106286	0x060ef000	0x062ef000	      2048	rw-        	full          	guarded_heap_area
	106260	0x07449000	0x07649000	      2048	rw-        	full          	guarded_heap_area
	106250	0x0aeef000	0x0b0ef000	      2048	rw-        	full          	guarded_heap_area
	106249	0x2d638000	0x2d838000	      2048	rw-        	full          	guarded_heap_area
	106246	0x2da65000	0x2dc65000	      2048	rw-        	full          	guarded_heap_area
	106257	0x60000000	0x60001000	         4	rw-S       	full          	server_memory
	106259	0x68000000	0x68025000	       148	rw-S       	full          	server_memory
	106262	0x70000000	0x70020000	       128	rw-S       	full          	server_memory
	106264	0x78000000	0x78058000	       352	rw-S       	full          	server_memory
	106266	0x80000000	0x80067000	       412	rw-S       	full          	server_memory
	106269	0x88000000	0x88058000	       352	rw-S       	full          	server_memory
	106271	0x90000000	0x90020000	       128	rw-S       	full          	server_memory
	106274	0x98000000	0x9809d000	       628	rw-S       	full          	server_memory
	106278	0xa0000000	0xa1097000	     16988	rw-S       	full          	server_memory
	106294	0xa8000000	0xa8028000	       160	rw-S       	full          	server_memory
	106297	0xb0000000	0xb0066000	       408	rw-S       	full          	server_memory
	106300	0xb8000000	0xb803e000	       248	rw-S       	full          	server_memory
	106303	0xc0000000	0xc0094000	       592	rw-S       	full          	server_memory
	106306	0xc8000000	0xc8039000	       228	rw-S       	full          	server_memory
	106308	0xd0000000	0xd0020000	       128	rw-S       	full          	server_memory
	106312	0xd8000000	0xd8104000	      1040	rw-S       	full          	server_memory
	106245	0xe76e9000	0xe77e9000	      1024	rw-        	full          	guarded_heap_area
	106314	0xe77e9000	0xe7811000	       160	rw-S       	full          	server_memory
	106316	0xef7e9000	0xef809000	       128	rw-S       	full          	server_memory
	106319	0xf77e9000	0xf7809000	       128	rw-S       	full          	server_memory
	106321	0xff7e9000	0xff809000	       128	rw-S       	full          	server_memory
	106323	0x1077e9000	0x107809000	       128	rw-S       	full          	server_memory
	106244	0x238d20000	0x238d38000	        96	rw-        	full          	rld heap
	106243	0x2cfed4000	0x2cfeec000	        96	rw-        	full          	rld heap
	106242	0x398402000	0x398412000	        64	rw-        	full          	rld heap
	106241	0x6716ab000	0x6716bb000	        64	rw-        	full          	rld heap
	106240	0x77dbc3000	0x77dbcb000	        32	rw-        	full          	rld heap
	106239	0xac839d000	0xac83a5000	        32	rw-        	full          	rld heap
	106192	0x1c6d64c000	0x1c6d7ae000	      1416	r-x        	full          	libstdc++.so.6.0.25_seg0ro
	106193	0x1c6d9ae000	0x1c6d9ba000	        48	rw-        	full          	libstdc++.so.6.0.25_seg1rw
	106194	0x1c6d9ba000	0x1c6d9c2000	        32	rw-        	full          	libstdc++.so.6.0.25_seg2rw
	106235	0x26dc362000	0x26dc3cc000	       424	r-x        	full          	libssl.so.1.0.0_seg0ro
	106236	0x26dc5cb000	0x26dc5d6000	        44	rw-        	full          	libssl.so.1.0.0_seg1rw
	106186	0x289187c000	0x289187d000	         4	rw-S       	full          	_rld_debug_
	106214	0x46ebcd7000	0x46ebd2c000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	106215	0x46ebf2c000	0x46ebf2f000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	106187	0x48cffc6000	0x48cfff3000	       180	r-x        	full          	StreamRadio_seg0ro
	106188	0x48d01f3000	0x48d01f6000	        12	rw-        	full          	StreamRadio_seg1rw
	106199	0x4e1c9c6000	0x4e1ca2c000	       408	r-x        	full          	libbnetapi.so_seg0ro
	106200	0x4e1cc2c000	0x4e1cc31000	        20	rw-        	full          	libbnetapi.so_seg1rw
	106206	0x544d104000	0x544d11a000	        88	r-x        	full          	libgcc_s.so.1_seg0ro
	106207	0x544d319000	0x544d31a000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	106185	0x56220c7000	0x56220d7000	        64	rw-        	full          	rld heap
	106229	0xc5e982f000	0xc5e9870000	       260	r-x        	full          	libnetwork.so_seg0ro
	106230	0xc5e9a6f000	0xc5e9a72000	        12	rw-        	full          	libnetwork.so_seg1rw
	106231	0xc5e9a72000	0xc5e9a78000	        24	rw-        	full          	libnetwork.so_seg2rw
	106212	0xc61c9e1000	0xc61c9ed000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	106213	0xc61cbec000	0xc61cbee000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	106210	0xd2daf1f000	0xd2db19c000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	106211	0xd2db39b000	0xd2db3b0000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	106227	0x1050cd02000	0x1050cdfd000	      1004	r-x        	full          	libtextencoding.so_seg0ro
	106228	0x1050cffd000	0x1050d000000	        12	rw-        	full          	libtextencoding.so_seg1rw
	106225	0x1134f0ce000	0x1134f1a1000	       844	r-x        	full          	libzstd.so.1.3.8_seg0ro
	106226	0x1134f3a1000	0x1134f3a2000	         4	rw-        	full          	libzstd.so.1.3.8_seg1rw
	106218	0x1207cf33000	0x1207cf62000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	106219	0x1207d162000	0x1207d164000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	106220	0x1207d164000	0x1207d196000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	106216	0x1343b45b000	0x1343b466000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	106217	0x1343b666000	0x1343b667000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	106201	0x14d70f78000	0x14d7102c000	       720	r-x        	full          	libmedia.so_seg0ro
	106202	0x14d7122c000	0x14d71238000	        48	rw-        	full          	libmedia.so_seg1rw
	106203	0x159f6f15000	0x159f706b000	      1368	r-x        	full          	libxml2.so.2.9.9_seg0ro
	106204	0x159f726b000	0x159f7276000	        44	rw-        	full          	libxml2.so.2.9.9_seg1rw
	106205	0x159f7276000	0x159f7278000	         8	rw-        	full          	libxml2.so.2.9.9_seg2rw
	106182	0x168cb9ff000	0x168cba20000	       132	r-x        	full          	runtime_loader_seg0ro
	106183	0x168cbc1f000	0x168cbc21000	         8	rw-        	full          	runtime_loader_seg1rw
	106184	0x168cbc21000	0x168cbc22000	         4	rw-        	full          	runtime_loader_bss1
	106197	0x189e00f9000	0x189e010e000	        84	r-x        	full          	libtranslation.so_seg0ro
	106198	0x189e030d000	0x189e030f000	         8	rw-        	full          	libtranslation.so_seg1rw
	106195	0x197e5e88000	0x197e61a0000	      3168	r-x        	full          	libbe.so_seg0ro
	106196	0x197e63a0000	0x197e63ce000	       184	rw-        	full          	libbe.so_seg1rw
	106221	0x1af075c5000	0x1af0775d000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	106222	0x1af0795c000	0x1af07971000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	106223	0x1bb699f8000	0x1bb69a14000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	106224	0x1bb69c13000	0x1bb69c14000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	106232	0x1c942fc2000	0x1c9431c4000	      2056	r-x        	full          	libcrypto.so.1.0.0_seg0ro
	106233	0x1c9433c3000	0x1c9433ea000	       156	rw-        	full          	libcrypto.so.1.0.0_seg1rw
	106234	0x1c9433ea000	0x1c9433ec000	         8	rw-        	full          	libcrypto.so.1.0.0_seg2rw
	106208	0x1ca93320000	0x1ca94b9e000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	106209	0x1ca94d9d000	0x1ca94d9e000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	106237	0x1da422fa000	0x1da42301000	        28	r-x        	full          	libbsd.so_seg0ro
	106238	0x1da42500000	0x1da42501000	         4	rw-        	full          	libbsd.so_seg1rw
	106189	0x1fffd733000	0x1fffd894000	      1412	r-x        	full          	libroot_debug.so_seg0ro
	106190	0x1fffda94000	0x1fffdaa2000	        56	rw-        	full          	libroot_debug.so_seg1rw
	106191	0x1fffdaa2000	0x1fffdae6000	       272	rw-        	full          	libroot_debug.so_seg2rw
	106336	0x7f44f8ccd000	0x7f44f8d12000	       276	rw-s       	full          	MouseTrackingThread_3032_stack
	106332	0x7fc9b4714000	0x7fc9b4759000	       276	rw-s       	full          	w>StreamRadio_3030_stack
	106179	0x7fe3a45e3000	0x7fe3a45e7000	        16	rw-        	full          	user area
	106180	0x7ffd046e5000	0x7ffd056eb000	     16408	rw-s       	full          	StreamRadio_3025_stack
	106181	0x7ffff6052000	0x7ffff605a000	        32	r-xS       	full          	commpage

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	136504	    0	       1391	tool tip manager
	136528	    0	          0	some BLocker
	136545	    0	       1392	_RWLocker_mutex
	136650	    0	       1391	BMessageQueue Lock
	136651	    0	       1391	offscreen bitmap
	136667	    0	       1391	some BBlockCache lock
	136668	    0	       1391	token space
	136669	    0	       1391	BLooperList lock
	136670	    0	       1391	AppServerLink_sLock
	136671	    0	       1391	some BLocker
	136672	    0	       1391	Catalog
	136674	    0	       1391	LocaleRosterData
	136675	    0	       1391	some BLocker
	136676	    0	       1391	Catalog
	136677	    0	       1391	DNS cache
	136678	    0	       1391	synchronized hash map
	136679	    0	       1391	synchronized hash map
	136680	    0	       1391	some BLocker
	136681	    0	       1391	some BLocker
	136682	    0	       1391	BMediaRoster::Roster locker
	136683	    0	       1391	media theme lock
	136684	    0	       1391	add-on manager
	136685	    0	       1391	port pool
	136686	    0	       1391	shared buffer list
	136687	    0	       1391	media plugin manager
	136688	    0	       1391	BMessageQueue Lock
	136689	    0	       1391	AppLooperPort
	136701	    0	       1391	screen list
	136702	    0	       1391	clipboard
	136703	    0	       1391	width buffer
	136705	    0	       1391	BMessageQueue Lock
	136706	   -1	       3030	StreamRadio
	136711	    0	       1391	offscreen bitmap
	136713	    0	       1391	BMessageQueue Lock
	136734	    0	          0	some BLocker
	136738	    0	          0	some BLocker
	136739	    0	       1425	some BLocker
	136741	    0	       1392	_RWLocker_queue

**Comment by Begasus** [comment]
Is this still valid, didn't experience any problems switching here

**Comment by jsteinaker** [comment]
Can someone please confirm is this is still valid? No problems here.

**Comment by humdingerb** [comment]
Not on 32bit for me, at least. Let's point Vidrep to this when we next see him on IRC before closing.

**Comment by humdingerb** [comment]
Vidrep will re-open this one, if he can reproduce. Said so on IRC.
