### ISSUE TITLE
No more scrollbar after Haiku hrev52809

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Haiku-Radio#5]
This commit has broken the scrollbar functionality on Radio: https://git.haiku-os.org/haiku/commit/?id=4854630d290208095d847eca34ad738653bf3cbc

**Comment by diversys** [comment]
@waddlesplash could you take a look?

**Comment by Vidrep** [comment]
Tested today with hrev53182 and scrollbar is working again. Closing.
