### ISSUE TITLE
StreamRadio crash when quit

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Haiku-Radio#9]
hrev53228 x86_64 StreamRadio 0.0.3_14-2

When quitting the application there is a crash. This version is the one found on HaikuDepot.

LD_PRELOAD=libroot_debug.so MALLOC_DEBUG=g StreamRadio
``
Debug information for team /boot/system/apps/StreamRadio (3201):
CPU(s): 8x Intel Core™ i7-3770
Memory: 15.88 GiB total, 902.92 MiB used
Haiku revision: hrev53238 Jul 10 2019 21:04:49 (x86_64)

Active Threads:
	thread 3201: StreamRadio (main)
	thread 3319: team 3201 debug task 
	thread 3206: w>StreamRadio 
		state: Call (thread 3206 tried accessing address 0x3c7af90 which is not allocated (base: 0x3c7af90, size: 112, alignment: 16, allocated by thread: 3201, freed by thread: 3206))

		Frame		IP			Function Name
		-----------------------------------------------
		00000000	0x33eec82e7f	_kern_debugger + 0x7 
			Disassembly:
				_kern_debugger:
				0x00000033eec82e78:   48c7c0e1000000  mov $0xe1, %rax
				0x00000033eec82e7f:             0f05  syscall  <--

		0x7f85716927a0	0x33eed2c25d	panic(char const*, ...) + 0xad 
		0x7f8571692800	0x33eed2c8a8	guarded_heap_segfault_handler(int, __siginfo_t*, void*) + 0x148 
		0x7f8571692800	0x7fffffa4823b	commpage_signal_handler + 0x2b 
		0x7f8571692bf0	0xcc0e1581f9	BInvoker::SetMessage(BMessage*) + 0x19 
		0x7f8571692c10	0xcc0e18cb1e	BControl::~BControl() + 0x5e 
		0x7f8571692c30	0xcc0e1deaac	BSlider::~BSlider() + 0xc 
		0x7f8571692c50	0xcc0e20cce7	BView::~BView() + 0x47 
		0x7f8571692c70	0x219396f15ec	StationPanel::~StationPanel() + 0xc 
		0x7f8571692c90	0xcc0e20cce7	BView::~BView() + 0x47 
		0x7f8571692cb0	0xcc0e20cdcc	BView::~BView() + 0xc 
		0x7f8571692d10	0xcc0e214441	BWindow::~BWindow() + 0xc1 
		0x7f8571692d30	0x219396e83ec	MainWindow::~MainWindow() + 0xc 
		0x7f8571692d60	0xcc0e15bcde	BLooper::Quit() + 0x6e 
		0x7f8571692e10	0xcc0e15be2c	BLooper::_QuitRequested(BMessage*) + 0x3c 
		0x7f8571693040	0xcc0e2178d9	BWindow::DispatchMessage(BMessage*, BHandler*) + 0x89 
		0x7f85716930d0	0xcc0e2139eb	BWindow::task_looper() + 0x1bb 
		0x7f85716930f0	0xcc0e15aa6b	BLooper::_task0_(void*) + 0x1b 
		0x7f8571693110	0x33eec81c27	thread_entry + 0x17 
		00000000	0x7fffffa48260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x00000033eec82e81
			  rsp:	0x00007f85716922a8
			  rbp:	0x00007f8571692790
			  rax:	0x00000000000000e1
			  rbx:	0x00007f85716922d0
			  rcx:	0x00000033eec82e81
			  rdx:	0x00007f8571691e43
			  rsi:	0x0000000000000001
			  rdi:	0x00007f85716922d0
			   r8:	0x0000000000000002
			   r9:	0x00000000ffffff5e
			  r10:	0x00007f85716922d0
			  r11:	0x0000000000003202
			  r12:	0x0000000000000070
			  r13:	0x0000000000000010
			  r14:	0x0000000000000c81
			  r15:	0x0000000000000c86
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	0
			  st1:	0
			  st2:	0
			  st3:	0
			  st4:	0
			  st5:	0
			  st6:	0
			  st7:	0
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0, 0, 0, 0}
			  mm2:	{0, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0, 0, 0}
			  mm6:	{0, 0, 0, 0}
			  mm7:	{0, 0, 0, 0}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	9988	0x621645000	0x62165b000	0x62185a000	0x62185b000	lib    	/boot/system/lib/libgcc_s.so.1
	9985	0x1e500eb000	0x1e50151000	0x1e50351000	0x1e50356000	lib    	/boot/system/lib/libbnetapi.so
	9981	0x33eec41000	0x33eeda2000	0x33eefa2000	0x33eeff4000	lib    	/boot/system/lib/libroot_debug.so
	10002	0x5001ee8000	0x5001eef000	0x50020ee000	0x50020ef000	lib    	/boot/system/lib/libbsd.so
	9995	0x7c4a3e1000	0x7c4a579000	0x7c4a778000	0x7c4a78d000	lib    	/boot/system/lib/libicuuc.so.57.1
	9991	0x7f1ac41000	0x7f1ac4d000	0x7f1ae4c000	0x7f1ae4e000	lib    	/boot/system/lib/libicuio.so.57.1
	9998	0x89f6c6b000	0x89f6d66000	0x89f6f66000	0x89f6f69000	lib    	/boot/system/lib/libtextencoding.so
	9986	0x8b57bbf000	0x8b57c73000	0x8b57e73000	0x8b57e7f000	lib    	/boot/system/lib/libmedia.so
	9983	0xcc0e003000	0xcc0e31b000	0xcc0e51b000	0xcc0e549000	lib    	/boot/system/lib/libbe.so
	9999	0x10d1653f000	0x10d16580000	0x10d1677f000	0x10d16788000	lib    	/boot/system/lib/libnetwork.so
	9997	0x10ec891c000	0x10ec89ef000	0x10ec8bef000	0x10ec8bf0000	lib    	/boot/system/lib/libzstd.so.1.3.8
	9987	0x11c83df3000	0x11c83f49000	0x11c84149000	0x11c84156000	lib    	/boot/system/lib/libxml2.so.2.9.9
	9989	0x1223c1dd000	0x1223da5b000	0x1223dc5a000	0x1223dc5b000	lib    	/boot/system/lib/libicudata.so.57.1
	9982	0x12537c7e000	0x12537de0000	0x12537fe0000	0x12537ff4000	lib    	/boot/system/lib/libstdc++.so.6.0.25
	9979	0x1318c8ef000	0x1318c910000	0x1318cb0f000	0x1318cb12000	lib    	/boot/system/runtime_loader
	10001	0x1ac0eef4000	0x1ac0ef5e000	0x1ac0f15d000	0x1ac0f168000	lib    	/boot/system/lib/libssl.so.1.0.0
	9996	0x1aeac289000	0x1aeac2a5000	0x1aeac4a4000	0x1aeac4a5000	lib    	/boot/system/lib/libz.so.1.2.11
	10000	0x1c96df5f000	0x1c96e161000	0x1c96e360000	0x1c96e389000	lib    	/boot/system/lib/libcrypto.so.1.0.0
	9994	0x1e1c62d7000	0x1e1c6306000	0x1e1c6506000	0x1e1c653a000	lib    	/boot/system/lib/libicutu.so.57.1
	9992	0x1ed6602d000	0x1ed66082000	0x1ed66282000	0x1ed66285000	lib    	/boot/system/lib/libicule.so.57.1
	9990	0x1edc0e67000	0x1edc10e4000	0x1edc12e3000	0x1edc12f8000	lib    	/boot/system/lib/libicui18n.so.57.1
	9993	0x20481a44000	0x20481a4f000	0x20481c4f000	0x20481c50000	lib    	/boot/system/lib/libiculx.so.57.1
	9984	0x2064ec62000	0x2064ec77000	0x2064ee76000	0x2064ee78000	lib    	/boot/system/lib/libtranslation.so
	9980	0x219396ce000	0x219396f9000	0x219398f9000	0x219398fc000	app    	/boot/system/apps/StreamRadio
	9978	0x7fffffa48000	0x7fffffa50000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	113318	0x0022e000	0x0042e000	      2048	rw-        	full          	guarded_heap_area
	113323	0x004ee000	0x006ee000	      2048	rw-        	full          	guarded_heap_area
	113308	0x0072b000	0x0092b000	      2048	rw-        	full          	guarded_heap_area
	113335	0x00ab5000	0x00cb5000	      2048	rw-        	full          	guarded_heap_area
	113326	0x00d18000	0x00f18000	      2048	rw-        	full          	guarded_heap_area
	113339	0x00fa0000	0x011a0000	      2048	rw-        	full          	guarded_heap_area
	113336	0x012a1000	0x014a1000	      2048	rw-        	full          	guarded_heap_area
	113350	0x01596000	0x01796000	      2048	rw-        	full          	guarded_heap_area
	113307	0x0184d000	0x01a4d000	      2048	rw-        	full          	guarded_heap_area
	113366	0x01a89000	0x01c89000	      2048	rw-        	full          	guarded_heap_area
	113365	0x01cd2000	0x01ed2000	      2048	rw-        	full          	guarded_heap_area
	113364	0x01fe4000	0x021e4000	      2048	rw-        	full          	guarded_heap_area
	113367	0x0220f000	0x0240f000	      2048	rw-        	full          	guarded_heap_area
	113363	0x024e8000	0x026e8000	      2048	rw-        	full          	guarded_heap_area
	113394	0x02735000	0x02935000	      2048	rw-        	full          	guarded_heap_area
	113385	0x02940000	0x02b40000	      2048	rw-        	full          	guarded_heap_area
	113378	0x02c1e000	0x02e1e000	      2048	rw-        	full          	guarded_heap_area
	113377	0x02e9c000	0x0309c000	      2048	rw-        	full          	guarded_heap_area
	113445	0x030e9000	0x032e9000	      2048	rw-        	full          	guarded_heap_area
	113444	0x0336f000	0x0356f000	      2048	rw-        	full          	guarded_heap_area
	113415	0x035e0000	0x037e0000	      2048	rw-        	full          	guarded_heap_area
	113558	0x037e9000	0x039e9000	      2048	rw-        	full          	guarded_heap_area
	113374	0x03a8c000	0x03c8c000	      2048	rw-        	full          	guarded_heap_area
	113583	0x03d60000	0x03f60000	      2048	rw-        	full          	guarded_heap_area
	113584	0x04341000	0x04541000	      2048	rw-        	full          	guarded_heap_area
	113371	0x04a43000	0x04c43000	      2048	rw-        	full          	guarded_heap_area
	113370	0x08f73000	0x09173000	      2048	rw-        	full          	guarded_heap_area
	113369	0x15ac5000	0x15cc5000	      2048	rw-        	full          	guarded_heap_area
	113368	0x15ef9000	0x160f9000	      2048	rw-        	full          	guarded_heap_area
	113356	0x16f7e000	0x1717e000	      2048	rw-        	full          	guarded_heap_area
	113353	0x24bd6000	0x24dd6000	      2048	rw-        	full          	guarded_heap_area
	113304	0x25194000	0x25394000	      2048	rw-        	full          	guarded_heap_area
	113303	0x31191000	0x31291000	      1024	rw-        	full          	guarded_heap_area
	113302	0x40f24000	0x40f3c000	        96	rw-        	full          	rld heap
	113315	0x60000000	0x60001000	         4	rw-S       	full          	server_memory
	113317	0x68000000	0x68050000	       320	rw-S       	full          	server_memory
	113320	0x70000000	0x70058000	       352	rw-S       	full          	server_memory
	113322	0x78000000	0x7806a000	       424	rw-S       	full          	server_memory
	113325	0x80000000	0x80114000	      1104	rw-S       	full          	server_memory
	113330	0x88000000	0x884a4000	      4752	rw-S       	full          	server_memory
	113334	0x90000000	0x901a5000	      1684	rw-S       	full          	server_memory
	113301	0x9a12c000	0x9a144000	        96	rw-        	full          	rld heap
	113338	0x9a144000	0x9a225000	       900	rw-S       	full          	server_memory
	113341	0xa2144000	0xa219c000	       352	rw-S       	full          	server_memory
	113343	0xaa144000	0xaa169000	       148	rw-S       	full          	server_memory
	113345	0xb2144000	0xb2169000	       148	rw-S       	full          	server_memory
	113349	0xba144000	0xba31c000	      1888	rw-S       	full          	server_memory
	113352	0xc2144000	0xc2189000	       276	rw-S       	full          	server_memory
	113355	0xca144000	0xca18b000	       284	rw-S       	full          	server_memory
	113358	0xd2144000	0xd21c1000	       500	rw-S       	full          	server_memory
	113362	0xda144000	0xdaa57000	      9292	rw-S       	full          	server_memory
	113300	0x1032c3000	0x1032d3000	        64	rw-        	full          	rld heap
	113299	0x12e5b7000	0x12e5c7000	        64	rw-        	full          	rld heap
	113298	0x140dc4000	0x140dcc000	        32	rw-        	full          	rld heap
	113297	0x40ad03000	0x40ad0b000	        32	rw-        	full          	rld heap
	113264	0x621645000	0x62165b000	        88	r-x        	full          	libgcc_s.so.1_seg0ro
	113265	0x62185a000	0x62185b000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	113244	0x6bdb0a000	0x6bdb0b000	         4	rw-S       	full          	_rld_debug_
	113257	0x1e500eb000	0x1e50151000	       408	r-x        	full          	libbnetapi.so_seg0ro
	113258	0x1e50351000	0x1e50356000	        20	rw-        	full          	libbnetapi.so_seg1rw
	113247	0x33eec41000	0x33eeda2000	      1412	r-x        	full          	libroot_debug.so_seg0ro
	113248	0x33eefa2000	0x33eefb0000	        56	rw-        	full          	libroot_debug.so_seg1rw
	113249	0x33eefb0000	0x33eeff4000	       272	rw-        	full          	libroot_debug.so_seg2rw
	113295	0x5001ee8000	0x5001eef000	        28	r-x        	full          	libbsd.so_seg0ro
	113296	0x50020ee000	0x50020ef000	         4	rw-        	full          	libbsd.so_seg1rw
	113243	0x524c894000	0x524c8a4000	        64	rw-        	full          	rld heap
	113279	0x7c4a3e1000	0x7c4a579000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	113280	0x7c4a778000	0x7c4a78d000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	113270	0x7f1ac41000	0x7f1ac4d000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	113271	0x7f1ae4c000	0x7f1ae4e000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	113285	0x89f6c6b000	0x89f6d66000	      1004	r-x        	full          	libtextencoding.so_seg0ro
	113286	0x89f6f66000	0x89f6f69000	        12	rw-        	full          	libtextencoding.so_seg1rw
	113259	0x8b57bbf000	0x8b57c73000	       720	r-x        	full          	libmedia.so_seg0ro
	113260	0x8b57e73000	0x8b57e7f000	        48	rw-        	full          	libmedia.so_seg1rw
	113253	0xcc0e003000	0xcc0e31b000	      3168	r-x        	full          	libbe.so_seg0ro
	113254	0xcc0e51b000	0xcc0e549000	       184	rw-        	full          	libbe.so_seg1rw
	113287	0x10d1653f000	0x10d16580000	       260	r-x        	full          	libnetwork.so_seg0ro
	113288	0x10d1677f000	0x10d16782000	        12	rw-        	full          	libnetwork.so_seg1rw
	113289	0x10d16782000	0x10d16788000	        24	rw-        	full          	libnetwork.so_seg2rw
	113283	0x10ec891c000	0x10ec89ef000	       844	r-x        	full          	libzstd.so.1.3.8_seg0ro
	113284	0x10ec8bef000	0x10ec8bf0000	         4	rw-        	full          	libzstd.so.1.3.8_seg1rw
	113261	0x11c83df3000	0x11c83f49000	      1368	r-x        	full          	libxml2.so.2.9.9_seg0ro
	113262	0x11c84149000	0x11c84154000	        44	rw-        	full          	libxml2.so.2.9.9_seg1rw
	113263	0x11c84154000	0x11c84156000	         8	rw-        	full          	libxml2.so.2.9.9_seg2rw
	113266	0x1223c1dd000	0x1223da5b000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	113267	0x1223dc5a000	0x1223dc5b000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	113250	0x12537c7e000	0x12537de0000	      1416	r-x        	full          	libstdc++.so.6.0.25_seg0ro
	113251	0x12537fe0000	0x12537fec000	        48	rw-        	full          	libstdc++.so.6.0.25_seg1rw
	113252	0x12537fec000	0x12537ff4000	        32	rw-        	full          	libstdc++.so.6.0.25_seg2rw
	113240	0x1318c8ef000	0x1318c910000	       132	r-x        	full          	runtime_loader_seg0ro
	113241	0x1318cb0f000	0x1318cb11000	         8	rw-        	full          	runtime_loader_seg1rw
	113242	0x1318cb11000	0x1318cb12000	         4	rw-        	full          	runtime_loader_bss1
	113293	0x1ac0eef4000	0x1ac0ef5e000	       424	r-x        	full          	libssl.so.1.0.0_seg0ro
	113294	0x1ac0f15d000	0x1ac0f168000	        44	rw-        	full          	libssl.so.1.0.0_seg1rw
	113281	0x1aeac289000	0x1aeac2a5000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	113282	0x1aeac4a4000	0x1aeac4a5000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	113290	0x1c96df5f000	0x1c96e161000	      2056	r-x        	full          	libcrypto.so.1.0.0_seg0ro
	113291	0x1c96e360000	0x1c96e387000	       156	rw-        	full          	libcrypto.so.1.0.0_seg1rw
	113292	0x1c96e387000	0x1c96e389000	         8	rw-        	full          	libcrypto.so.1.0.0_seg2rw
	113276	0x1e1c62d7000	0x1e1c6306000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	113277	0x1e1c6506000	0x1e1c6508000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	113278	0x1e1c6508000	0x1e1c653a000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	113272	0x1ed6602d000	0x1ed66082000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	113273	0x1ed66282000	0x1ed66285000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	113268	0x1edc0e67000	0x1edc10e4000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	113269	0x1edc12e3000	0x1edc12f8000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	113274	0x20481a44000	0x20481a4f000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	113275	0x20481c4f000	0x20481c50000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	113255	0x2064ec62000	0x2064ec77000	        84	r-x        	full          	libtranslation.so_seg0ro
	113256	0x2064ee76000	0x2064ee78000	         8	rw-        	full          	libtranslation.so_seg1rw
	113245	0x219396ce000	0x219396f9000	       172	r-x        	full          	StreamRadio_seg0ro
	113246	0x219398f9000	0x219398fc000	        12	rw-        	full          	StreamRadio_seg1rw
	113380	0x7f8571650000	0x7f8571695000	       276	rw-s       	full          	w>StreamRadio_3206_stack
	113238	0x7fccb1ac8000	0x7fccb2ace000	     16408	rw-s       	full          	StreamRadio_3201_stack
	113237	0x7fd1ec15f000	0x7fd1ec163000	        16	rw-        	full          	user area
	113239	0x7fffffa48000	0x7fffffa50000	        32	r-xS       	full          	commpage

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	428042	    0	       2427	some BLocker
	441354	    0	       2427	LocaleRosterData
	467819	    0	       2427	token space
	467856	    0	       2427	BLooperList lock
	467870	    0	       2427	some BLocker
	467875	    0	       2427	some BBlockCache lock
	467880	    0	       2427	some BLocker
	467883	    0	       2427	AppServerLink_sLock
	467968	    0	       2427	Catalog
	467992	    0	       2427	DNS cache
	467999	    0	       2427	synchronized hash map
	468000	    0	       2427	synchronized hash map
	468001	    0	       2427	Catalog
	468003	    0	       2427	some BLocker
	468004	    0	       2427	BMediaRoster::Roster locker
	468005	    0	       2427	media theme lock
	468006	    0	       2427	some BLocker
	468008	    0	       2427	port pool
	468009	    0	       2427	shared buffer list
	468010	    0	       2427	media plugin manager
	468011	    0	       2427	add-on manager
	468014	    0	       2427	BMessageQueue Lock
	468017	    0	       2427	AppLooperPort
	468020	    0	       2427	BMessageQueue Lock
	468030	   -1	       2427	StreamRadio
	468032	    0	       2427	screen list
	468033	    0	       2427	clipboard
	468034	    0	       2427	width buffer
	468040	    0	       2427	BMessageQueue Lock
	468041	    0	       2427	offscreen bitmap
	468056	    0	       2427	BMessageQueue Lock
	468057	    0	       2427	offscreen bitmap
	468069	    0	       2427	tool tip manager
``

**Comment by jsteinaker** [comment]
This is already fixed in https://github.com/jsteinaker/Haiku-Radio/commit/8cc9fa4139f0f9cc71b609d9e724b34a58baa26a

Compile with gcc7 if you want to try it before I try to fix the code for gcc8
